Ember branch
ArtistMonkey83/PavilionTestHarness pull request #10
Opened 2020-07-16 21:32 UTC by ckendric

Hotspotinc and Randominc tests have short runtimes, I tried editing the inputs but only got segfault errors (even when I gave the default values). All other tests have increased runtimes, except ping pong which only can use defaults.

2020-07-16 22:12 UTC, jennfshr requested changes
Phew, this is a beast.  I think you've done a great job with carving out the individual tests.  My comments inline are about trying to refine the test to not need redirection to a file, then parsing that file, removing _no_build and _build (sorry, again) and making _build just be the way we approach it in general.  if you remove the `v` from the tar extract commands, it will save some unneeded output in the build.log.  Get this stuff fixed up, and we'll do another review.  Nice job @ckendric

2020-07-16 22:12 UTC, jennfshr commented on ProxyAppsSuite/tests/ember.yaml
> +            #- cp ../../openmpi-3.1.5.tar.bz2 .  || (echo "$0 at $LINENO FAILED"; exit 1;)
remove this line

2020-07-16 22:12 UTC, jennfshr commented on ProxyAppsSuite/tests/ember.yaml
> +
I recommend moving the mpi test builds into this spot, too.

2020-07-16 22:12 UTC, jennfshr commented on ProxyAppsSuite/tests/ember.yaml
> +            - srun -n 8 ./halo3d-26 -nx 700 -ny 700 -nz 700 -pex 4 -pey 2 -pez 1 -iterations 1000 -vars 20 -sleep 2000 &> halo3d-26.out
Since each test is a distinct test in itself, can we just have the output go to stdout rather than redirecting to a file?

2020-07-16 22:12 UTC, jennfshr commented on ProxyAppsSuite/tests/ember.yaml
> +            - mv halo3d-26.out ../../halo3d-26.out
Lines 83/84 are unneeded if you agree about letting stdout goto the run.log

2020-07-16 22:12 UTC, jennfshr commented on ProxyAppsSuite/tests/ember.yaml
> +                files: halo3d-26.out
the files: key can be omitted if we let go to run.log

2020-07-16 22:12 UTC, jennfshr commented on ProxyAppsSuite/tests/ember.yaml
> +            - srun -n 8 ./halo3d -nx 700 -ny 700 -nz 700 -pex 4 -pey 2 -pez 1 -iterations 1000 -vars 20 -sleep 2000 &> halo3d.out
Same here, recommend letting it goto stdout (i.e., run.log)

2020-07-16 22:12 UTC, jennfshr commented on ProxyAppsSuite/tests/ember.yaml
> +            - 'cd shmem/hotspotinc || (echo "$0 at $LINENO FAILED" ; exit 1 ;)'
I'm still trying to refine this, as I found that when the `cmd || ( cmd; exit 1; )` doesn't really do what we want it to do.  I recommend removing it until we can figure out a solid plan for that.

2020-07-16 22:12 UTC, jennfshr commented on ProxyAppsSuite/tests/ember.yaml
> +    inherits_from: _no_build
I'm starting to think that we should get rid of the _no_build/_build approach, and just build it everywhere... may make it simpler. (sorry!)

2020-07-16 22:12 UTC, jennfshr commented on ProxyAppsSuite/tests/ember.yaml
> +    summary: Large scale modeling of high-performance interconnects
Does it model without the SST simulator to ingest the results?  may change this to mpi and shmem performance tests.

2020-07-16 22:12 UTC, jennfshr commented on ProxyAppsSuite/tests/ember.yaml
> +            - 'tar xvfz ucx-1.8.0.tar.gz &> ucx-build.log'
make this line (line 15) `- 'tar xfz ucx-1.8.0.tar.gz` - don't redirect. I tried setting up redirection everywhere, removed it, but forgot this line.

2020-07-16 22:12 UTC, jennfshr commented on ProxyAppsSuite/tests/ember.yaml
> +            - 'find ../openmpi/3.1.5/platform -name "toss3-mlx-optimized.conf" '
we should try to rename this file, and remove the other mpi version subdirs from the test_src before we put a big ribbon on this test.

2020-07-20 17:31 UTC, francinelapid commented
```bash
wc-fe1:ProxyAppsS $ pav run ember
Resolving Test Configs: 100%
Could not create builder for test ember.halo3d-26 (run 1): Could not find source 'ember2'
```

Can we include the build cmds for ember? I didn't have ember in my `test_src` dir

2020-07-20 19:41 UTC, ckendric commented
Fixed that issue. It confused the source directory for another github repo so it wasn't working the way I intended

2020-07-23 16:00 UTC, francinelapid requested changes

2020-07-23 16:00 UTC, francinelapid commented on ProxyAppsSuite/tests/ember.yaml
> +        source_path: ember
The build finally works! To simplify things, instead of including the entire ember source code in the PR, can we try something like this?

```suggestion
        source_path: ember
        source_url: https://github.com/sstsimulator/ember/archive/master.zip
```

Pavilion should download the zipfile and place it into `test_src/ember`

2020-07-23 16:00 UTC, francinelapid commented on ProxyAppsSuite/tests/ember.yaml
> +            - srun --mpi=pmix -n 8 ./halo3d -nx 700 -ny 700 -nz 700 -pex 4 -pey 2 -pez 1 -iterations 1000 -vars 20 -sleep 2000
```suggestion
            - "{{sched.test_cmd}} --mpi=pmix -n 8 ./halo3d -nx 700 -ny 700 -nz 700 -pex 4 -pey 2 -pez 1 -iterations 1000 -vars 20 -sleep 2000"
```

Can we change `srun`s to `"{{sched.test_cmd}}"`? In case we decide to override the scheduler and use something like `mpirun` instead.

2020-07-23 16:00 UTC, francinelapid commented on ProxyAppsSuite/tests/ember.yaml
> +                action: 'store_true'
If this is they key that determines whether a test completely passes or not, we should change `passed` to `result` (also replace in every other sub-test)

```suggestion
            result:
                regex: '\#\sResults\sfrom\srank\:\s+(\d)'
                action: 'store_true'
```

2020-07-23 16:12 UTC, ckendric commented on ProxyAppsSuite/tests/ember.yaml
> +        source_path: ember
Unfortuantley not, as some lines needed to be changed inside of the makefiles for randominc and hotspotinc, so they are not the same as their source github.

2020-07-23 16:57 UTC, ckendric commented on ProxyAppsSuite/tests/ember.yaml
> +            - srun --mpi=pmix -n 8 ./halo3d -nx 700 -ny 700 -nz 700 -pex 4 -pey 2 -pez 1 -iterations 1000 -vars 20 -sleep 2000
I did this for all but the shmemrun commands, which are separate from the scheduler commands

2020-07-23 17:37 UTC, francinelapid approved these changes

2020-07-28 19:48 UTC, merged